/*

 */

pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds')
        DOCKER_REGISTRY = 'tomertest123'
        REPO_NAME = 'fe-exam'  // Change to 'be-exam' for backend pipeline
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        
    }
    stages {
        stage('Clone Repository') { // clone the repository
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/tomerk122/devopshift-welcome.git'
            }
        } // end of clone repository
        stage('Lint & Security Scan') {
            parallel {
                stage('Flake8 Linting') {
                    steps {
                        // sh 'pip install flake8'
                        // sh 'flake8 .'
                       sh 'echo "bandit -r ."'
                    }
                }
                stage('Bandit Security Scan') {
                    steps {
                        // sh 'pip install bandit'
                        // sh 'bandit -r .'
                     sh 'echo "bandit -r ."'
                    }
                }
            }
        } // end of lint & security scan
        stage('Install Dependencies') { // Install dependencies based on repo name
                steps {
                    script {
                        if (env.REPO_NAME == 'fe-exam') {
                            // dir('exam-code/docker/fe') {
                            //     sh 'pwd'
                            //     sh 'pip install -r requirements.txt'
                            // }
                            sh 'docker --version'

                        } else {
                            dir('exam-code/docker/be') { 
                                sh 'pwd'
                                sh 'pip install -r requirements.txt'
                            }
                        }
                    }
                }
            } // end of install dependencies
        stage('Build Docker Image'){
        steps {
            agent{label 'docker'}
            script {
                if (env.REPO_NAME == 'fe-exam') {
                    dir('exam-code/docker/fe') {
                        sh 'docker build -t ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} .'
                        sh 'docker tag ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} ${DOCKER_REGISTRY}/${REPO_NAME}:latest'
                    }
                } else {
                    dir('exam-code/docker/be') {
                        sh 'docker build -t ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} .'
                        sh 'docker tag ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} ${DOCKER_REGISTRY}/${REPO_NAME}:latest'
                    }
                }
            }
        }
    }
}
}
        
        
